# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: point.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bpoint.proto\x12\x05point\"p\n\x12\x41\x64\x64\x41\x63tivityRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x14\n\x0cpoint_impact\x18\x03 \x01(\x05\x12\x13\n\x0b\x63\x61tegory_id\x18\x04 \x01(\x05\x12\x0c\n\x04type\x18\x05 \x01(\t\",\n\x10\x41\x63tivityResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\"G\n\x15RecordActivityRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x11\n\tuser_hash\x18\x02 \x01(\t\x12\r\n\x05nonce\x18\x03 \x01(\t\"$\n\x12UserPointsResponse\x12\x0e\n\x06points\x18\x01 \x01(\x05\")\n\x14GetUserPointsRequest\x12\x11\n\tuser_hash\x18\x01 \x01(\t2\xe5\x01\n\x0cPointService\x12\x41\n\x0b\x41\x64\x64\x41\x63tivity\x12\x19.point.AddActivityRequest\x1a\x17.point.ActivityResponse\x12I\n\x0eRecordActivity\x12\x1c.point.RecordActivityRequest\x1a\x19.point.UserPointsResponse\x12G\n\rGetUserPoints\x12\x1b.point.GetUserPointsRequest\x1a\x19.point.UserPointsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'point_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDACTIVITYREQUEST']._serialized_start=22
  _globals['_ADDACTIVITYREQUEST']._serialized_end=134
  _globals['_ACTIVITYRESPONSE']._serialized_start=136
  _globals['_ACTIVITYRESPONSE']._serialized_end=180
  _globals['_RECORDACTIVITYREQUEST']._serialized_start=182
  _globals['_RECORDACTIVITYREQUEST']._serialized_end=253
  _globals['_USERPOINTSRESPONSE']._serialized_start=255
  _globals['_USERPOINTSRESPONSE']._serialized_end=291
  _globals['_GETUSERPOINTSREQUEST']._serialized_start=293
  _globals['_GETUSERPOINTSREQUEST']._serialized_end=334
  _globals['_POINTSERVICE']._serialized_start=337
  _globals['_POINTSERVICE']._serialized_end=566
# @@protoc_insertion_point(module_scope)
