# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: promo.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bpromo.proto\x12\x05promo\"+\n\x13ProductPromoRequest\x12\x14\n\x0cproduct_hash\x18\x01 \x01(\t\"\xdb\x01\n\x14ProductPromoResponse\x12\x14\n\x0chas_discount\x18\x01 \x01(\x08\x12\x13\n\x0b\x66inal_price\x18\x02 \x01(\x01\x12\x0f\n\x07is_bogo\x18\x03 \x01(\x08\x12/\n\x12\x62uy_x_get_y_promos\x18\x04 \x03(\x0b\x32\x13.promo.BuyXGetYInfo\x12\x1d\n\x15\x62undle_product_hashes\x18\x05 \x03(\t\x12\x1e\n\x16\x63\x61n_purchase_by_points\x18\x06 \x01(\x08\x12\x17\n\x0fpoints_required\x18\x07 \x01(\x05\"h\n\x0c\x42uyXGetYInfo\x12\x1d\n\x15required_product_hash\x18\x01 \x01(\t\x12\x1f\n\x17\x64iscounted_product_hash\x18\x02 \x01(\t\x12\x18\n\x10\x64iscounted_price\x18\x03 \x01(\x01\")\n\x15ThresholdPromoRequest\x12\x10\n\x08subtotal\x18\x01 \x01(\x01\"M\n\x16ThresholdPromoResponse\x12\x1b\n\x13has_threshold_promo\x18\x01 \x01(\x08\x12\x16\n\x0e\x64iscount_value\x18\x02 \x01(\x01\x32\xaf\x01\n\x0cPromoService\x12K\n\x10GetProductPromos\x12\x1a.promo.ProductPromoRequest\x1a\x1b.promo.ProductPromoResponse\x12R\n\x13\x43heckThresholdPromo\x12\x1c.promo.ThresholdPromoRequest\x1a\x1d.promo.ThresholdPromoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'promo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTPROMOREQUEST']._serialized_start=22
  _globals['_PRODUCTPROMOREQUEST']._serialized_end=65
  _globals['_PRODUCTPROMORESPONSE']._serialized_start=68
  _globals['_PRODUCTPROMORESPONSE']._serialized_end=287
  _globals['_BUYXGETYINFO']._serialized_start=289
  _globals['_BUYXGETYINFO']._serialized_end=393
  _globals['_THRESHOLDPROMOREQUEST']._serialized_start=395
  _globals['_THRESHOLDPROMOREQUEST']._serialized_end=436
  _globals['_THRESHOLDPROMORESPONSE']._serialized_start=438
  _globals['_THRESHOLDPROMORESPONSE']._serialized_end=515
  _globals['_PROMOSERVICE']._serialized_start=518
  _globals['_PROMOSERVICE']._serialized_end=693
# @@protoc_insertion_point(module_scope)
